apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: miolacar
spec:
  serviceName: mariadb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "springboot"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: root-password
          livenessProbe:
            exec:
              command: ["mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            exec:
              command: ["mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-data