apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: miolacar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434
          livenessProbe:
            exec:
              command: ["ollama", "list"]
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 20
          readinessProbe:
            exec:
              command: ["ollama", "list"]
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-data