apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: miolacar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # tinyllama ~637MB + marge